# Generated by Django 4.2.16 on 2025-10-15 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='customer',
            field=models.ForeignKey(help_text='The customer following the vendor.', on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='follow',
            name='vendor',
            field=models.ForeignKey(help_text='The vendor being followed.', on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='users.vendorprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('customer', 'vendor')},
        ),
    ]
