# Generated by Django 5.2.6 on 2025-09-21 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('followers', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to='users.customerprofile'),
        ),
        migrations.AddField(
            model_name='follow',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='users.vendorprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('customer', 'vendor')},
        ),
    ]
