# Generated by Django 4.2.16 on 2025-10-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the product.', max_length=100)),
                ('description', models.TextField(blank=True, help_text='A description of the product (optional).')),
                ('price', models.DecimalField(decimal_places=2, help_text='The price of the product in the local currency.', max_digits=10)),
                ('quantity', models.PositiveIntegerField(help_text='The available stock quantity of the product.')),
                ('image', models.ImageField(blank=True, help_text='An optional image of the product.', null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the product was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the product was last updated.')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
