# Generated by Django 5.2.6 on 2025-10-05 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_shed_product_shed'),
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vendors.shed'),
        ),
        migrations.DeleteModel(
            name='Shed',
        ),
    ]
