# Generated by Django 4.2.16 on 2025-10-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='The number of product units preordered.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', help_text='The current status of the preorder (pending, confirmed, or cancelled).', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the preorder was created.')),
            ],
            options={
                'verbose_name': 'Preorder',
                'verbose_name_plural': 'Preorders',
            },
        ),
    ]
