# Generated by Django 4.2.16 on 2025-10-15 00:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='customer',
            field=models.ForeignKey(help_text='The customer profile placing the preorder.', on_delete=django.db.models.deletion.CASCADE, related_name='preorders', to='users.customerprofile'),
        ),
        migrations.AddField(
            model_name='preorder',
            name='product',
            field=models.ForeignKey(help_text='The product being preordered.', on_delete=django.db.models.deletion.CASCADE, related_name='preorders', to='products.product'),
        ),
        migrations.AddField(
            model_name='preorder',
            name='vendor',
            field=models.ForeignKey(help_text='The vendor user associated with the product.', on_delete=django.db.models.deletion.CASCADE, related_name='vendor_preorders', to=settings.AUTH_USER_MODEL),
        ),
    ]
