# Generated by Django 4.2.16 on 2025-10-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The payment amount in the local currency.', max_digits=10)),
                ('reference', models.CharField(help_text='The unique Paystack transaction reference.', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', help_text='The current status of the payment (pending, success, or failed).', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the payment was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the payment was last updated.')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='VendorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='The payment amount in the local currency.', max_digits=10)),
                ('reference', models.CharField(help_text='The unique Paystack transaction reference.', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', help_text='The current status of the payment (pending, success, or failed).', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the payment was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the payment was last updated.')),
            ],
            options={
                'verbose_name': 'Vendor Payment',
                'verbose_name_plural': 'Vendor Payments',
            },
        ),
    ]
