# Generated by Django 4.2.16 on 2025-10-15 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        ('payments', '0001_initial'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpayment',
            name='shed',
            field=models.ForeignKey(help_text='The shed associated with this payment.', on_delete=django.db.models.deletion.CASCADE, related_name='vendor_payments', to='vendors.shed'),
        ),
        migrations.AddField(
            model_name='payment',
            name='preorder',
            field=models.ForeignKey(help_text='The preorder associated with this payment.', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.preorder'),
        ),
    ]
