# Generated by Django 4.2.16 on 2025-10-24 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shed_number', models.CharField(help_text='Unique identifier for the shed.', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Name of the shed.', max_length=100)),
                ('domain', models.CharField(choices=[('CB', 'Clothings and Beddings'), ('EC', 'Electronics and Computer wares'), ('FB', 'Food and Beverages'), ('JA', 'Jewelry and Accessories')], help_text='Category/domain of the shed.', max_length=2)),
                ('secured', models.BooleanField(default=False, help_text='Whether the shed is secured (e.g., payment completed).')),
                ('collage', models.ImageField(blank=True, help_text='Image collage of products in the shed.', null=True, upload_to='shed_collages/')),
                ('vendor', models.ForeignKey(help_text='The vendor owning this shed.', on_delete=django.db.models.deletion.CASCADE, related_name='sheds', to='users.vendorprofile')),
            ],
            options={
                'verbose_name': 'Shed',
                'verbose_name_plural': 'Sheds',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the product.', max_length=100)),
                ('description', models.TextField(help_text='Description of the product.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the product in NGN.', max_digits=10)),
                ('image', models.ImageField(blank=True, help_text='Optional image of the product.', null=True, upload_to='product_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the product was added.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the product was last updated.')),
                ('shed', models.ForeignKey(help_text='The shed containing this product.', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='vendors.shed')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
