# Generated by Django 5.2.6 on 2025-09-21 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('CL', 'Clothing and Bedding'), ('FB', 'Food and Beverages'), ('JC', 'Jewelries and Accessories'), ('EC', 'Electronics and Computer Wares')], max_length=2)),
                ('shed_number', models.CharField(editable=False, max_length=6, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheds', to='users.vendorprofile')),
            ],
        ),
    ]
