# Generated by Django 5.2.6 on 2025-10-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shed',
            name='secured',
            field=models.BooleanField(default=False),
        ),
    ]
