# Generated by Django 4.2.16 on 2025-10-22 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shed',
            name='domain',
        ),
    ]
