# Generated by Django 5.2.6 on 2025-10-11 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_shed_secured'),
    ]

    operations = [
        migrations.AddField(
            model_name='shed',
            name='collage',
            field=models.ImageField(blank=True, null=True, upload_to='shed_collages/'),
        ),
    ]
