# Generated by Django 4.2.16 on 2025-10-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='shed_number',
            field=models.CharField(help_text='Unique shed number (e.g., JA1, CB1) within the domain.', max_length=10, unique=True),
        ),
    ]
