# Generated by Django 4.2.16 on 2025-10-22 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_preorder_customer'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
    ]
