# Generated by Django 4.2.16 on 2025-10-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_customerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='domain',
            field=models.CharField(choices=[('CB', 'Clothings and Beddings'), ('EC', 'Electronics and Computer wares'), ('FB', 'Food abd Beverages'), ('JA', 'Jewelry and Accessories')], default='CB', help_text='Category/domain of the shed.', max_length=2),
            preserve_default=False,
        ),
    ]
