# Generated by Django 4.2.16 on 2025-10-22 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_vendorprofile_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='shed_number',
            field=models.PositiveIntegerField(blank=True, help_text='Unique shed number (1-100) within the domain.', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='domain',
            field=models.CharField(choices=[('CB', 'Clothings and Beddings'), ('EC', 'Electronics and Computer wares'), ('FB', 'Food and Beverages'), ('JA', 'Jewelry and Accessories')], help_text='Category/domain of the shed.', max_length=2),
        ),
        migrations.AddConstraint(
            model_name='vendorprofile',
            constraint=models.UniqueConstraint(fields=('domain', 'shed_number'), name='unique_shed_per_domain'),
        ),
    ]
