# Generated by Django 4.2.16 on 2025-10-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_vendorprofile_shed_number_alter_vendorprofile_domain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(help_text="The user's first name.", max_length=150),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(help_text="The user's last name.", max_length=150),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='shed_number',
            field=models.PositiveIntegerField(default=1, help_text='Unique shed number (1-100) within the domain.', unique=True),
            preserve_default=False,
        ),
    ]
